version: '3.8'
services:
  nextjs:
    build: .
    volumes:
      - .:/app
      - /app/node_modules # Ensure node_modules are not overwritten
    ports:
      - "3000:3000"
    command: npm run dev
